### ISSUE TITLE
Issue with 2-factor AUTH with google

### ISSUE THREAD

**Issue by tbomb34** [jcoutch/usg-scripts#3]
I have created an app password for my USG with google using your scripts because I have 2 factor enabled.  I am getting an authorization failure.  My connection does not seem to be using tls with smtp.gmail.com.  I am using port 587.  Need your help.  Regards.

**Comment by G-eos** [comment]
Hello,
To work you need if you enable 2FTA to create an application password. And then configure like explained. Please can you post your conf here (without the credential and your email ) ?

I am using it without trouble so far.
You can log into the USG and check the content of /etc/ssmtp files.
 And then check with 
/usr/sbin/ssmtp "Your email" < /etc/ssmtp/revaliases -v
with the -v you will have some debug hint.

If you whish I am enhancing the script, please check the push request ;-) and confirm that it works.

**Comment by tbomb34** [comment]
G-eos, thanks for your reply.  I set up a 2 factor app with Google for this.  I put in the password they supplied and am using port 587.  My authuser is the first part of my Gmail account without @gmail.com
